version: '3.7'
services:
  # PostgreSQL service
  apptrackerdb:
    image: postgres:15.4
    container_name: postgres
    env_file:
      - ./postgres.env
    volumes:
      - ./db-init-scripts:/docker-entrypoint-initdb.d
  # RabbitMQ service
  rabbitmq:
    image: "rabbitmq:3.12-management"
    container_name: rabbitmq
    env_file:
      - ./rabbit.env
    ports:
      - "5672:5672"      # AMQP protocol
      - "15672:15672"    # Management console
  # Telegram bot
  telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile_bot
    env_file:
      - ./bot.env
    depends_on:
      - apptrackerdb
      - rabbitmq
    restart: always
