version: "3.7"
services:
  fetcher:
    build:
      context: .
      dockerfile: Dockerfile_fetcher
    privileged: true
    volumes:
      - ./output:/code/output
    env_file:
      - ./fetcher.env
    restart: always