version: '3.7'
services:
  # PostgreSQL service
  apptrackerdb:
    image: postgres:15.4
    container_name: postgres
    environment:
      POSTGRES_DB: AppTrackerDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./db-init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
  # RabbitMQ service
  rabbitmq:
    image: "rabbitmq:3.12-management"
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: bunny_admin
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672"      # AMQP protocol
      - "15672:15672"    # Management console
  # Telegram bot
  telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile_bot
    env_file:
      - ./bot.env
    depends_on:
      - apptrackerdb
      - rabbitmq
    restart: always
