name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Setup Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    # Login to Docker Hub
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Build and push bot image
    - name: Build and push bot Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile_bot
        push: true
        tags: olegeech/mvcr-application-checker:bot-latest

    # Build and push fetcher image
    - name: Build and push fetcher Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile_fetcher
        push: true
        tags: olegeech/mvcr-application-checker:fetcher-latest
